package com.octopus.calamari.tomcathttps

object AttributeDatabase {
    /**
     * A list of <Connector> attributes
     */
    val connectorAttribuites
        get() = listOf("allowTrace",
                "asyncTimeout",
                "enableLookups",
                "maxHeaderCount",
                "maxParameterCount",
                "maxPostSize",
                "maxSavePostSize",
                "parseBodyMethods",
                "port",
                "protocol",
                "proxyName",
                "proxyPort",
                "redirectPort",
                "scheme",
                "secure",
                "URIEncoding",
                "useBodyEncodingForURI",
                "useIPVHosts",
                "xpoweredBy",
                "acceptCount",
                "acceptorThreadCount",
                "acceptorThreadPriority",
                "address",
                "allowedTrailerHeaders",
                "bindOnInit",
                "compressibleMimeType",
                "compression",
                "compressionMinSize",
                "connectionLinger",
                "connectionTimeout",
                "connectionUploadTimeout",
                "disableUploadTimeout",
                "executor",
                "executorTerminationTimeoutMillis",
                "keepAliveTimeout",
                "maxConnections",
                "maxCookieCount",
                "maxExtensionSize",
                "maxHttpHeaderSize",
                "maxKeepAliveRequests",
                "maxSwallowSize",
                "maxThreads",
                "maxTrailerSize",
                "minSpareThreads",
                "noCompressionUserAgents",
                "processorCache",
                "restrictedUserAgents",
                "server",
                "socketBuffer",
                "SSLEnabled",
                "tcpNoDelay",
                "threadPriority",
                "upgradeAsyncWriteBufferSize",
                "socket.rxBufSize",
                "socket.txBufSize",
                "socket.tcpNoDelay",
                "socket.soKeepAlive",
                "socket.ooBInline",
                "socket.soReuseAddress",
                "socket.soLingerOn",
                "socket.soLingerTime",
                "socket.soTimeout",
                "socket.performanceConnectionTime",
                "socket.performanceLatency",
                "socket.performanceBandwidth",
                "socket.unlockTimeout",
                "disableKeepAlivePercentage",
                "pollerThreadCount",
                "pollerThreadPriority",
                "selectorTimeout",
                "useComet",
                "useSendfile",
                "socket.directBuffer",
                "socket.appReadBufSize",
                "socket.appWriteBufSize",
                "socket.bufferPool",
                "socket.bufferPoolSize",
                "socket.processorCache",
                "socket.keyCache",
                "socket.eventCache",
                "selectorPool.maxSelectors",
                "selectorPool.maxSpareSelectors",
                "command-line-options",
                "oomParachute",
                "deferAccept",
                "pollerSize",
                "pollTime",
                "sendfileSize",
                "threadPriority",
                "useComet",
                "useSendfile",
                "socket.directSslBuffer", // start of options new in tomcat 8
                "useCaches",
                "useComet",
                "useSendfile",
                "socket.directBuffer",
                "socket.directSslBuffer",
                "socket.appReadBufSize",
                "socket.appWriteBufSize",
                "socket.bufferPoolSize",
                "socket.processorCache",
                "socket.socketWrapperCache",
                "oomParachute",
                "pollerThreadCount",
                "sendfileThreadCount", // start of options new in tomcat 8.5
                "defaultSSLHostConfigName",
                "sendReasonPhrase",
                "clientCertProvider",
                "serverRemoveAppProvidedValues",
                "socket.bufferPool",
                "ipv6v6only",
                "throwOnFailure") // start of options new in tomcat 9


    /**
     * A list of the attributes that may conflict with the configuration we are defining
     */
    val conflictingAttributes
        get() = listOf("certificateKeyFile",
                "certificateFile",
                "certificateKeyAlias",
                "certificateKeyPassword",
                "certificateKeystoreFile",
                "certificateKeystorePassword",
                "certificateKeystoreProvider",
                "certificateKeystoreType",
                "SSLCertificateFile",
                "SSLCertificateKeyFile",
                "SSLPassword",
                "keyAlias",
                "keyPass",
                "keystoreFile",
                "keystorePass",
                "keystoreProvider",
                "keystoreType")

    /**
     * A list of JSSE only attributes in tomcat 8.5 and 9
     */
    val tomcat85JSEEOnlyAttributes
        get() = listOf("keyManagerAlgorithm",
                "algorithm",
                "revocationEnabled",
                "sessionCacheSize",
                "sessionTimeout",
                "sslProtocol",
                "trustManagerClassName",
                "truststoreAlgorithm",
                "truststoreFile",
                "truststorePassword",
                "truststorePass",
                "truststoreProvider",
                "truststoreType",
                "certificateKeyAlias",
                "keyAlias",
                "certificateKeystoreFile",
                "keystoreFile",
                "certificateKeystorePassword",
                "keystorePass",
                "certificateKeystoreProvider",
                "keystoreProvider",
                "certificateKeystoreType",
                "keystoreType")

    /**
     * A list of OpenSSL only attributes in tomcat 8.5 and 9
     */
    val tomcat85OpenSSLOnlyAttributes
        get() = listOf("certificateRevocationFile", // tomcat 8.5
                "certificateRevocationListFile", // tomcat 9
                "SSLCARevocationFile",
                "crlFile",
                "certificateRevocationPath", // tomcat 8.5
                "certificateRevocationListPath", // tomcat 9
                "SSLCARevocationPath",
                "caCertificateFile",
                "SSLCACertificateFile",
                "caCertificatePath",
                "SSLCACertificatePath",
                "disableCompression",
                "SSLDisableCompression",
                "disableSessionTickets",
                "SSLDisableSessionTickets",
                "insecureRenegotiation")
}